package main

import (
	"encoding/json"
	"fmt"
)

type AutoGenerated struct {
	Name    string   `json:"name"`
	Hobbies []string `json:"hobbies"`
	Books   struct {
		Num1 string `json:"1"`
		Num2 string `json:"2"`
		Num3 string `json:"3"`
	} `json:"books"`
}

func main() {
	var jsontoslice []AutoGenerated
	jsonString := `[{"name":"Razi","hobbies":["Badminton","Games"],"books":{"1":"Atomic Habits","2":"The Intelligent Investor","3":"Supernova"}},{"name":"Syahputro","hobbies":["Football","Boxing"],"books":{"1":"The Lord of The Ring","2":"Harry Potter","3":"The Great Gatsby"}}]`
	jsonBytes := []byte(jsonString)

	json.Unmarshal(jsonBytes, &jsontoslice)
	fmt.Println(jsontoslice)
}
