package main

import (
	"encoding/json"
	"fmt"
)

type AutoGenerated struct {
	Name      string         `json:"name"`
	Hobbies   []string       `json:"hobbies"`
	Books     map[int]string `json:"books"` //for unpredictable the key's objects
	Addresses []struct {
		Name       string `json:"name"`
		Street     string `json:"street"`
		Country    string `json:"country"`
		PostalCode string `json:"postalcode"`
	} `json:"address"`
}

func main() {
	var jsontoslice []AutoGenerated
	jsonString := `[{"name":"Razi","hobbies":["Badminton","Games"],"books":{"1":"Atomic Habits","2":"The Intelligent Investor","3":"Supernova"},"address":[{"name":"Home","street":"Jl. Nusantara","country":"Indonesia","postalcode":"14444"},{"name":"Office","street":"Jl. Megapolitan","country":"Indonesia","postalcode":"14440"}]},{"name":"Syahputro","hobbies":["Football","Boxing"],"books":{"1":"The Lord of The Ring","2":"Harry Potter","3":"The Great Gatsby"},"address":null}]`
	jsonBytes := []byte(jsonString)

	json.Unmarshal(jsonBytes, &jsontoslice)
	fmt.Println(jsontoslice)
}
